"""tft_attrs_schemas — F-series (T1) per-component attribute schemas.

Generated from ``findings/attrs-raw.txt`` (which itself was extracted from
``hmitype.dll``'s ``GuiObj<Kind>.GetAtts_WithNoHead`` IL). Each entry is
``(attr_name, attpos, type_name)`` where:

- ``attpos`` is the byte offset within the component's ``PianyiData`` block
  (offset from ``sizeof(<Kind>_PARAM_Head)``).
- ``type_name`` is one of the keys in ``ATTSHULEI_BY_NAME`` in
  ``tft_attrs_encoder``.

The list order is the order ``GetAtts_WithNoHead`` declares attributes,
which is the order ``mpage.refallatt()`` enumerates them for the per-page
record table.

To regenerate, run ``scripts/tools/regen_attrs_schemas.py``.
"""

TYPE_SCHEMAS: dict[str, list[tuple[str, int, str]]] = {
    'GuiObjAudio': [
        ('from', 24, 'Select'),
        ('vid', 1, 'Audioid'),
        ('path', 28, 'Sstr'),
        ('path_m', 26, 'Strlenth'),
        ('en', 2, 'UU8'),
        ('loop', 3, 'Select'),
        ('fps', 4, 'UU8'),
        ('dis', 6, 'UU16'),
        ('tim', 8, 'SS32'),
        ('stim', 12, 'SS32'),
        ('qty', 20, 'SS32'),
        ('molloc_s', 32, 'SS32'),
        ('molloc', 36, 'SS32'),
    ],
    'GuiObjButton': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('pic', 6, 'Picid'),
        ('picc', 6, 'Picid'),
        ('bco', 6, 'Color'),
        ('pic2', 8, 'Picid'),
        ('picc2', 8, 'Picid'),
        ('bco2', 8, 'Color'),
        ('pco', 10, 'Color'),
        ('pco2', 12, 'Color'),
        ('xcen', 14, 'Select'),
        ('ycen', 15, 'Select'),
        ('val', 16, 'UU8'),
        ('txt', 20, 'Sstr'),
        ('txt_maxl', 18, 'Strlenth'),
        ('isbr', 24, 'Select'),
        ('spax', 25, 'UU8'),
        ('spay', 26, 'UU8'),
    ],
    'GuiObjButtonVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 1, 'UU16'),
        ('mode', 2, 'Select'),
        ('format', 33, 'Select'),
        ('write', 4, 'SS32'),
        ('dis', 4, 'SS32'),
        ('ch', 4, 'SS32'),
        ('loop', 43, 'Select'),
        ('up', 3, 'Select'),
        ('maxval', 8, 'SS32'),
        ('minval', 12, 'SS32'),
        ('vvs0', 44, 'Select'),
        ('sta', 16, 'Select'),
        ('style', 17, 'Select'),
        ('borderc', 18, 'Color'),
        ('borderw', 20, 'UU8'),
        ('font', 21, 'Fontid'),
        ('pic', 22, 'Picid'),
        ('picc', 22, 'Picid'),
        ('bco', 22, 'Color'),
        ('pic2', 24, 'Picid'),
        ('picc2', 24, 'Picid'),
        ('bco2', 24, 'Color'),
        ('pco', 26, 'Color'),
        ('pco2', 28, 'Color'),
        ('xcen', 30, 'Select'),
        ('ycen', 31, 'Select'),
        ('val', 32, 'UU8'),
        ('txt', 36, 'Sstr'),
        ('txt_maxl', 34, 'Strlenth'),
        ('isbr', 40, 'Select'),
        ('spax', 41, 'UU8'),
        ('spay', 42, 'UU8'),
    ],
    'GuiObjButton_T': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('pic', 6, 'Picid'),
        ('picc', 6, 'Picid'),
        ('bco', 6, 'Color'),
        ('pic2', 8, 'Picid'),
        ('picc2', 8, 'Picid'),
        ('bco2', 8, 'Color'),
        ('pco', 10, 'Color'),
        ('pco2', 12, 'Color'),
        ('xcen', 14, 'Select'),
        ('ycen', 15, 'Select'),
        ('val', 16, 'UU8'),
        ('txt', 20, 'Sstr'),
        ('txt_maxl', 18, 'Strlenth'),
        ('isbr', 24, 'Select'),
        ('spax', 25, 'UU8'),
        ('spay', 26, 'UU8'),
    ],
    'GuiObjCheckBox': [
        ('style', 1, 'Select'),
        ('borderw', 1, 'UU8'),
        ('borderc', 2, 'Color'),
        ('bco', 4, 'Color'),
        ('pco', 6, 'Color'),
        ('val', 8, 'UU8'),
    ],
    'GuiObjColPic': [
        ('write', 1, 'SS32'),
        ('close', 4, 'SS32'),
        ('buffsize', 8, 'SS32'),
        ('buff', 12, 'binary'),
    ],
    'GuiObjComboBox': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('bco', 6, 'Color'),
        ('picc', 6, 'Picid'),
        ('pic', 6, 'Picid'),
        ('pco', 8, 'Color'),
        ('xcen', 10, 'Select'),
        ('ycen', 11, 'Select'),
        ('spax', 12, 'UU8'),
        ('dis', 13, 'UU8'),
        ('txt', 16, 'Sstr'),
        ('txt_maxl', 14, 'Strlenth'),
        ('up', 20, 'Select'),
        ('pco3', 22, 'Color'),
        ('bco1', 26, 'Color'),
        ('pco1', 28, 'Color'),
        ('path', 32, 'Sstr'),
        ('path_m', 30, 'Strlenth'),
        ('dir', 36, 'Select'),
        ('qty', 37, 'UU8'),
        ('vvs0', 38, 'UU8'),
        ('val', 39, 'UU8'),
        ('bco2', 40, 'Color'),
        ('pco2', 42, 'Color'),
        ('hig', 44, 'UU8'),
        ('down', 45, 'Select'),
        ('mode', 46, 'Select'),
        ('wid', 47, 'UU8'),
        ('vvs1', 48, 'UU8'),
        ('ch', 49, 'UU8'),
        ('drastate', 50, 'UU8'),
    ],
    'GuiObjCurve': [
        ('sta', 1, 'Select'),
        ('dir', 1, 'Select'),
        ('ch', 2, 'Select'),
        ('bco', 4, 'Color'),
        ('picc', 4, 'Picid'),
        ('pic', 4, 'Picid'),
        ('gdc', 6, 'Color'),
        ('gdw', 8, 'UU8'),
        ('gdh', 9, 'UU8'),
        ('objWid', 10, 'UU16'),
        ('objHig', 12, 'UU16'),
        ('pco0', 14, 'Color'),
        ('pco1', 16, 'Color'),
        ('pco2', 18, 'Color'),
        ('pco3', 20, 'Color'),
        ('inittrue', 22, 'UU8'),
        ('dis', 24, 'UU16'),
        ('molloc_s', 28, 'SS32'),
        ('molloc', 32, 'SS32'),
    ],
    'GuiObjCurveVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 0, 'UU16'),
        ('mode', 1, 'Select'),
        ('vvs0', 1, 'UU16'),
        ('val', 1, 'UU16'),
        ('pco', 1, 'Color'),
        ('dis', 1, 'UU16'),
        ('ch', 1, 'UU8'),
        ('vvs1', 1, 'UU8'),
    ],
    'GuiObjDataRecord': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('bco', 6, 'Color'),
        ('picc', 6, 'Picid'),
        ('pic', 6, 'Picid'),
        ('pco', 8, 'Color'),
        ('xcen', 10, 'Select'),
        ('init', 11, 'UU8'),
        ('path', 16, 'Sstr'),
        ('path_m', 14, 'Strlenth'),
        ('lenth', 20, 'SS32'),
        ('maxval', 24, 'SS32'),
        ('dez', 28, 'UU16'),
        ('format', 32, 'Sstr'),
        ('format_m', 30, 'Strlenth'),
        ('dir', 40, 'Sstr'),
        ('dir_m', 38, 'Strlenth'),
        ('mode', 44, 'Select'),
        ('dis', 45, 'Select'),
        ('order', 46, 'Select'),
        ('qty', 48, 'SS32'),
        ('spax', 52, 'UU8'),
        ('hig', 53, 'UU8'),
        ('autoleft', 54, 'UU8'),
        ('left', 55, 'Select'),
        ('gdc', 56, 'Color'),
        ('gdw', 58, 'UU8'),
        ('gdh', 59, 'UU8'),
        ('bco1', 60, 'Color'),
        ('pco1', 62, 'Color'),
        ('bco2', 64, 'Color'),
        ('pco2', 66, 'Color'),
        ('filter', 72, 'Sstr'),
        ('filter_m', 70, 'Strlenth'),
        ('val', 76, 'SS32'),
        ('txt', 84, 'Sstr'),
        ('txt_m', 82, 'Strlenth'),
        ('insert', 88, 'SS32'),
        ('delete', 92, 'SS32'),
        ('up', 96, 'SS32'),
        ('clear', 100, 'SS32'),
        ('ch', 104, 'UU8'),
        ('maxval_y', 108, 'SS32'),
        ('val_y', 112, 'SS32'),
        ('maxval_x', 116, 'SS32'),
        ('val_x', 120, 'SS32'),
        ('molloc_s', 124, 'SS32'),
        ('molloc', 128, 'SS32'),
    ],
    'GuiObjDraVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 1, 'UU16'),
        ('dis', 1, 'UU8'),
        ('sta', 1, 'Select'),
    ],
    'GuiObjExPic': [
        ('path', 4, 'Sstr'),
        ('path_m', 2, 'Strlenth'),
    ],
    'GuiObjFileBrowser': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('bco', 6, 'Color'),
        ('picc', 6, 'Picid'),
        ('pic', 6, 'Picid'),
        ('pco', 8, 'Color'),
        ('pco2', 10, 'Color'),
        ('bco2', 12, 'Color'),
        ('xcen', 14, 'Select'),
        ('autoleft', 15, 'UU8'),
        ('left', 16, 'Select'),
        ('ch', 17, 'UU8'),
        ('dir', 20, 'Sstr'),
        ('dir_m', 18, 'Strlenth'),
        ('filter', 28, 'Sstr'),
        ('filter_m', 26, 'Strlenth'),
        ('val', 32, 'SS32'),
        ('txt', 40, 'Sstr'),
        ('txt_m', 38, 'Strlenth'),
        ('qty', 44, 'SS32'),
        ('dis', 48, 'UU8'),
        ('spax', 50, 'UU8'),
        ('spay', 51, 'UU8'),
        ('maxval_y', 52, 'SS32'),
        ('val_y', 56, 'SS32'),
        ('psta', 61, 'Select'),
        ('pic1', 62, 'Picid'),
        ('pic2', 64, 'Picid'),
        ('vvs2', 68, 'Sstr'),
        ('vvs2_m', 66, 'Strlenth'),
        ('buffsize', 72, 'SS32'),
        ('buff', 76, 'binary'),
        ('up', 80, 'SS32'),
        ('fwarning', 1, 'Select'),
    ],
    'GuiObjFileDirectory': [
        ('dir', 4, 'Sstr'),
        ('dir_m', 2, 'Strlenth'),
        ('filter', 12, 'Sstr'),
        ('filter_m', 10, 'Strlenth'),
        ('val', 16, 'SS32'),
        ('qty', 20, 'SS32'),
        ('txt', 28, 'Sstr'),
        ('txt_maxl', 26, 'Strlenth'),
        ('buffsize', 32, 'SS32'),
        ('buff', 36, 'binary'),
    ],
    'GuiObjFileStream': [
        ('val', 1, 'SS32'),
        ('qty', 4, 'SS32'),
        ('en', 8, 'UU8'),
        ('open', 12, 'SS32'),
        ('read', 16, 'SS32'),
        ('write', 20, 'SS32'),
        ('close', 24, 'SS32'),
        ('find', 28, 'SS32'),
        ('molloc_s', 32, 'SS32'),
        ('molloc', 36, 'SS32'),
    ],
    'GuiObjGText': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('key', 1, 'key'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('bco', 6, 'Color'),
        ('picc', 6, 'Picid'),
        ('pic', 6, 'Picid'),
        ('pco', 8, 'Color'),
        ('xcen', 10, 'Select'),
        ('ycen', 11, 'Select'),
        ('dir', 12, 'Select'),
        ('dis', 13, 'UU8'),
        ('tim', 14, 'UU16'),
        ('en', 16, 'UU8'),
        ('txt', 20, 'Sstr'),
        ('txt_maxl', 18, 'Strlenth'),
        ('isbr', 24, 'Select'),
        ('spax', 25, 'UU8'),
        ('spay', 26, 'UU8'),
        ('vvs0', 28, 'SS16'),
        ('vvs1', 30, 'SS16'),
        ('vvs2', 32, 'SS16'),
        ('vvs3', 34, 'SS16'),
    ],
    'GuiObjGmov': [
        ('from', 24, 'Select'),
        ('vid', 1, 'Gmovid'),
        ('path', 28, 'Sstr'),
        ('path_m', 26, 'Strlenth'),
        ('en', 2, 'UU8'),
        ('loop', 3, 'Select'),
        ('dis', 6, 'UU16'),
        ('tim', 8, 'SS32'),
        ('stim', 12, 'SS32'),
        ('qty', 20, 'SS32'),
        ('molloc_s', 32, 'SS32'),
        ('molloc', 36, 'SS32'),
    ],
    'GuiObjJPEGVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 1, 'UU16'),
        ('dis', 1, 'UU8'),
        ('sta', 1, 'Select'),
    ],
    'GuiObjMovepicVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 1, 'UU16'),
        ('en', 1, 'UU16'),
        ('stopval', 2, 'UU16'),
        ('playval', 4, 'UU16'),
        ('starpic', 6, 'Picid'),
        ('endpic', 8, 'Picid'),
        ('loop', 11, 'Select'),
        ('stopmode', 10, 'Select'),
        ('stoppic', 12, 'Picid'),
        ('sta', 14, 'Select'),
        ('tim', 16, 'UU16'),
    ],
    'GuiObjNum': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('key', 1, 'key'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('bco', 6, 'Color'),
        ('picc', 6, 'Picid'),
        ('pic', 6, 'Picid'),
        ('pco', 8, 'Color'),
        ('xcen', 10, 'Select'),
        ('ycen', 11, 'Select'),
        ('val', 12, 'SS32'),
        ('lenth', 16, 'UU8'),
        ('format', 17, 'Select'),
        ('isbr', 20, 'Select'),
        ('spax', 21, 'UU8'),
        ('spay', 22, 'UU8'),
    ],
    'GuiObjPage': [
        ('up', 1, 'UU8'),
        ('down', 1, 'UU8'),
        ('left', 2, 'UU8'),
        ('right', 3, 'UU8'),
        ('sta', 4, 'Select'),
        ('bco', 6, 'Color'),
        ('pic', 6, 'Picid'),
    ],
    'GuiObjPic': [
        ('pic', 1, 'Picid'),
    ],
    'GuiObjPicVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 1, 'UU16'),
        ('mode', 2, 'Select'),
        ('val', 1, 'UU16'),
        ('sta', 3, 'Select'),
        ('minval', 1, 'UU16'),
        ('maxval', 1, 'UU16'),
        ('pic0', 1, 'Picid'),
        ('pic1', 1, 'Picid'),
        ('vvs0', 4, 'Picid'),
        ('vvs1', 6, 'Picid'),
    ],
    'GuiObjPicc': [
        ('picc', 1, 'Picid'),
        ('vvs0', 2, 'SS16'),
        ('vvs1', 4, 'SS16'),
    ],
    'GuiObjPrinter3D': [
        ('en', 1, 'UU8'),
        ('sysinit', 1, 'UU8'),
        ('sta', 2, 'UU8'),
        ('mode', 3, 'UU8'),
        ('pw', 4, 'UU8'),
        ('val', 5, 'UU8'),
        ('pic', 6, 'Picid'),
        ('path', 12, 'Sstr'),
        ('path_m', 10, 'Strlenth'),
        ('dez', 16, 'SS32'),
        ('ch', 20, 'SS32'),
        ('tim', 24, 'SS32'),
        ('vid', 28, 'SS32'),
        ('vvs0', 32, 'SS32'),
        ('vvs1', 36, 'SS32'),
        ('vvs2', 40, 'SS32'),
        ('hig', 44, 'SS32'),
        ('dis', 48, 'SS32'),
        ('fps', 52, 'SS32'),
        ('disup', 56, 'SS32'),
        ('open', 60, 'SS32'),
        ('close', 64, 'SS32'),
        ('up', 68, 'SS32'),
        ('read', 72, 'SS32'),
        ('down', 76, 'SS32'),
        ('insert', 80, 'SS32'),
        ('molloc_s', 84, 'SS32'),
        ('molloc', 88, 'SS32'),
    ],
    'GuiObjProg': [
        ('sta', 1, 'Select'),
        ('dez', 1, 'Select'),
        ('val', 2, 'UU8'),
        ('dis', 3, 'UU8'),
        ('bco', 4, 'Color'),
        ('bpic', 4, 'Picid'),
        ('pco', 6, 'Color'),
        ('ppic', 6, 'Picid'),
    ],
    'GuiObjProgVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 1, 'UU16'),
        ('mode', 2, 'Select'),
        ('sta', 3, 'Select'),
        ('dez', 4, 'Select'),
        ('val', 1, 'SS16'),
        ('pic', 10, 'Picid'),
        ('dis', 5, 'UU8'),
        ('bco', 6, 'Color'),
        ('bpic', 6, 'Picid'),
        ('pco', 8, 'Color'),
        ('ppic', 8, 'Picid'),
    ],
    'GuiObjQrcode': [
        ('sta', 1, 'Select'),
        ('dis', 1, 'UU8'),
        ('bco', 2, 'Color'),
        ('pco', 4, 'Color'),
        ('pic', 6, 'Picid'),
        ('txt', 12, 'Sstr'),
        ('txt_maxl', 8, 'Strlenth'),
    ],
    'GuiObjQrcodeVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 1, 'UU16'),
        ('sta', 2, 'Select'),
        ('dis', 3, 'UU8'),
        ('bco', 4, 'Color'),
        ('pco', 6, 'Color'),
        ('pic', 8, 'Picid'),
        ('txt', 1, 'Sstr'),
        ('txt_maxl', 1, 'Strlenth'),
    ],
    'GuiObjRadio': [
        ('bco', 1, 'Color'),
        ('pco', 2, 'Color'),
        ('val', 4, 'UU8'),
    ],
    'GuiObjSLText': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('key', 1, 'key'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('bco', 6, 'Color'),
        ('picc', 6, 'Picid'),
        ('pic', 6, 'Picid'),
        ('pco', 8, 'Color'),
        ('xcen', 10, 'Select'),
        ('leftshow', 11, 'UU8'),
        ('left', 12, 'Select'),
        ('ch', 13, 'UU8'),
        ('txt', 16, 'Sstr'),
        ('txt_maxl', 14, 'Strlenth'),
        ('isbr', 20, 'Select'),
        ('spax', 21, 'UU8'),
        ('spay', 22, 'UU8'),
        ('path', 28, 'Sstr'),
        ('path_m', 26, 'Strlenth'),
        ('maxval_y', 36, 'SS32'),
        ('val_y', 40, 'SS32'),
    ],
    'GuiObjSlider': [
        ('mode', 1, 'Select'),
        ('sta', 1, 'Select'),
        ('psta', 2, 'Select'),
        ('wid', 3, 'UU8'),
        ('hig', 4, 'UU8'),
        ('dis', 5, 'UU8'),
        ('pic', 6, 'Picid'),
        ('picc', 6, 'Picid'),
        ('bco', 6, 'Color'),
        ('pic1', 22, 'Picid'),
        ('picc1', 22, 'Picid'),
        ('bco1', 22, 'Color'),
        ('pic2', 8, 'Picid'),
        ('pco', 8, 'Color'),
        ('val', 10, 'UU16'),
        ('maxval', 12, 'UU16'),
        ('minval', 14, 'UU16'),
        ('ch', 16, 'UU8'),
    ],
    'GuiObjSwitchbutton': [
        ('dez', 1, 'Select'),
        ('val', 1, 'UU8'),
        ('bco', 2, 'Color'),
        ('pco', 4, 'Color'),
        ('bco2', 6, 'Color'),
        ('pco2', 8, 'Color'),
        ('pco1', 10, 'Color'),
        ('font', 12, 'Fontid'),
        ('dis', 13, 'UU8'),
        ('txt', 16, 'Sstr'),
        ('txt_maxl', 14, 'Strlenth'),
    ],
    'GuiObjText': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('key', 1, 'key'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('bco', 6, 'Color'),
        ('picc', 6, 'Picid'),
        ('pic', 6, 'Picid'),
        ('pco', 8, 'Color'),
        ('xcen', 10, 'Select'),
        ('ycen', 11, 'Select'),
        ('pw', 12, 'Select'),
        ('txt', 16, 'Sstr'),
        ('txt_maxl', 14, 'Strlenth'),
        ('isbr', 20, 'Select'),
        ('spax', 21, 'UU8'),
        ('spay', 22, 'UU8'),
    ],
    'GuiObjTextSelect': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('bco', 6, 'Color'),
        ('picc', 6, 'Picid'),
        ('pic', 6, 'Picid'),
        ('pco', 8, 'Color'),
        ('pco2', 10, 'Color'),
        ('spax', 12, 'UU8'),
        ('hig', 13, 'UU8'),
        ('dis', 14, 'Select'),
        ('pco1', 16, 'Color'),
        ('txt', 20, 'Sstr'),
        ('txt_maxl', 18, 'Strlenth'),
        ('val', 24, 'SS32'),
        ('ch', 28, 'UU8'),
        ('path', 32, 'Sstr'),
        ('path_m', 30, 'Strlenth'),
    ],
    'GuiObjTextVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 1, 'UU16'),
        ('sta', 6, 'Select'),
        ('style', 7, 'Select'),
        ('key', 13, 'Pageid'),
        ('up', 14, 'Select'),
        ('borderc', 2, 'Color'),
        ('borderw', 8, 'UU8'),
        ('font', 1, 'Fontid'),
        ('bco', 4, 'Color'),
        ('picc', 4, 'Picid'),
        ('pic', 4, 'Picid'),
        ('pco', 1, 'Color'),
        ('xcen', 10, 'Select'),
        ('ycen', 11, 'Select'),
        ('pw', 9, 'Select'),
        ('txt', 1, 'Sstr'),
        ('txt_maxl', 1, 'Strlenth'),
        ('isbr', 12, 'Select'),
        ('spax', 1, 'UU8'),
        ('spay', 1, 'UU8'),
    ],
    'GuiObjTimer': [
        ('tim', 1, 'UU16'),
        ('en', 2, 'UU8'),
    ],
    'GuiObjTouchBsVP': [
        ('up', 6, 'Hex16'),
        ('sta', 1, 'Select'),
        ('pic', 2, 'Picid'),
        ('picc', 2, 'Picid'),
        ('bco', 2, 'Color'),
        ('pic2', 4, 'Picid'),
        ('picc2', 4, 'Picid'),
        ('bco2', 4, 'Color'),
        ('val', 1, 'UU8'),
    ],
    'GuiObjTouchMenuVP': [
        ('sta', 1, 'Select'),
        ('pic', 2, 'Picid'),
        ('picc', 2, 'Picid'),
        ('bco', 2, 'Color'),
        ('pic2', 4, 'Picid'),
        ('picc2', 4, 'Picid'),
        ('bco2', 4, 'Color'),
        ('val', 1, 'UU8'),
        ('VP', 6, 'UU16'),
        ('mode', 8, 'Select'),
        ('up', 9, 'Select'),
        ('key', 10, 'Pageid'),
        ('dir', 16, 'Sstr'),
        ('dir_m', 14, 'Strlenth'),
        ('pos', 24, 'Sstr'),
        ('pos_m', 22, 'Strlenth'),
    ],
    'GuiObjTouchUpVP': [
        ('up', 6, 'Hex16'),
        ('sta', 1, 'Select'),
        ('pic', 2, 'Picid'),
        ('picc', 2, 'Picid'),
        ('bco', 2, 'Color'),
        ('pic2', 4, 'Picid'),
        ('picc2', 4, 'Picid'),
        ('bco2', 4, 'Color'),
        ('mode', 8, 'Select'),
        ('vvs0', 9, 'Select'),
        ('val', 1, 'UU8'),
        ('once', 10, 'UU8'),
    ],
    'GuiObjTouchcap': [
        ('val', 1, 'UU8'),
    ],
    'GuiObjVari': [
        ('sta', 1, 'Select'),
        ('txt', 4, 'Sstr'),
        ('txt_maxl', 2, 'Strlenth'),
        ('val', 8, 'SS32'),
    ],
    'GuiObjVideo': [
        ('from', 24, 'Select'),
        ('vid', 1, 'Videoid'),
        ('path', 28, 'Sstr'),
        ('path_m', 26, 'Strlenth'),
        ('en', 2, 'UU8'),
        ('loop', 3, 'Select'),
        ('fps', 4, 'UU8'),
        ('dis', 6, 'UU16'),
        ('tim', 8, 'SS32'),
        ('stim', 12, 'SS32'),
        ('qty', 20, 'SS32'),
        ('molloc_s', 32, 'SS32'),
        ('molloc', 36, 'SS32'),
    ],
    'GuiObjXfloat': [
        ('sta', 1, 'Select'),
        ('style', 1, 'Select'),
        ('key', 1, 'key'),
        ('borderc', 2, 'Color'),
        ('borderw', 4, 'UU8'),
        ('font', 5, 'Fontid'),
        ('bco', 6, 'Color'),
        ('picc', 6, 'Picid'),
        ('pic', 6, 'Picid'),
        ('pco', 8, 'Color'),
        ('xcen', 10, 'Select'),
        ('ycen', 11, 'Select'),
        ('val', 12, 'SS32'),
        ('vvs0', 16, 'UU8'),
        ('vvs1', 17, 'UU8'),
        ('isbr', 20, 'Select'),
        ('spax', 21, 'UU8'),
        ('spay', 22, 'UU8'),
    ],
    'GuiObjXfloatVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 1, 'UU16'),
        ('mode', 1, 'Select'),
        ('sta', 2, 'Select'),
        ('style', 3, 'Select'),
        ('key', 13, 'Pageid'),
        ('up', 14, 'Select'),
        ('borderc', 4, 'Color'),
        ('borderw', 8, 'UU8'),
        ('font', 1, 'Fontid'),
        ('bco', 6, 'Color'),
        ('picc', 6, 'Picid'),
        ('pic', 6, 'Picid'),
        ('pco', 1, 'Color'),
        ('xcen', 1, 'Select'),
        ('ycen', 9, 'Select'),
        ('val', 1, 'SS16'),
        ('vvs0', 1, 'UU8'),
        ('vvs1', 1, 'UU8'),
        ('isbr', 10, 'Select'),
        ('spax', 11, 'UU8'),
        ('spay', 12, 'UU8'),
    ],
    'GuiObjYfloatVP': [
        ('RAM1', 1, 'UU16'),
        ('VP', 1, 'UU16'),
        ('mode', 2, 'Select'),
        ('vvs0', 3, 'UU8'),
        ('vvs1', 4, 'UU8'),
        ('xcen', 5, 'Select'),
        ('ycen', 6, 'Select'),
        ('pic', 8, 'Picid'),
        ('sta', 7, 'Select'),
        ('val', 1, 'SS16'),
    ],
    'GuiObjZhizhen': [
        ('sta', 1, 'Select'),
        ('picc', 2, 'Picid'),
        ('bco', 2, 'Color'),
        ('pic', 2, 'Picid'),
        ('val', 4, 'UU16'),
        ('format', 6, 'UU16'),
        ('up', 8, 'SS16'),
        ('down', 10, 'SS16'),
        ('left', 12, 'UU16'),
        ('pco', 14, 'Color'),
        ('pco2', 16, 'Color'),
        ('hig', 18, 'UU8'),
        ('wid', 20, 'UU8'),
        ('vvs0', 21, 'UU8'),
        ('vvs1', 22, 'UU8'),
        ('vvs2', 23, 'UU8'),
    ],
    'GuiObjinputTxtVP': [
        ('VP', 1, 'UU16'),
        ('lenth', 2, 'UU8'),
        ('key', 3, 'Pageid'),
        ('up', 4, 'Select'),
        ('pw', 5, 'Select'),
        ('mode', 6, 'Select'),
        ('path', 12, 'Sstr'),
        ('path_m', 10, 'Strlenth'),
    ],
    'GuiObjinputVP': [
        ('VP', 1, 'UU16'),
        ('mode', 2, 'Select'),
        ('vvs0', 3, 'UU8'),
        ('vvs1', 4, 'UU8'),
        ('key', 7, 'Pageid'),
        ('lenth', 16, 'UU8'),
        ('up', 5, 'Select'),
        ('pw', 6, 'Select'),
        ('maxval', 8, 'SS32'),
        ('minval', 12, 'SS32'),
        ('path', 20, 'Sstr'),
        ('path_m', 18, 'Strlenth'),
    ],
}


def get_schema(class_name: str) -> list[tuple[str, int, str]]:
    """Return the F-series ``GetAtts_WithNoHead`` schema for ``class_name``.

    Raises ``KeyError`` if the class is not in the table.
    """
    return TYPE_SCHEMAS[class_name]
